apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfonyapp-deployment
  namespace: default
  labels:
    app: symfonyapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfonyapp-deployment
  template:
    metadata:
      labels:
        app: symfonyapp-deployment
    spec:
      containers:
      - name: symfonyapp-container
        image: saif1198/symfonyapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: symfonyapp-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9000  # Mappé au port d'exposition du conteneur
  selector:
    app: symfonyapp-deployment