apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfonyapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfonyapp-deployment
  template:
    metadata:
      labels:
        app: symfonyapp-deployment
    spec:
      containers:
      - name: symfonyapp-deployment
        image: saif1198/symfonyapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: symfonyapp-service
spec:
  selector:
    app: symfonyapp-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort