apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfonyapp-deployment
  namespace: default
  labels:
    app: symfonyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfonyapp
  template:
    metadata:
      labels:
        app: symfonyapp
    spec:
      containers:
      - name: symfonyapp-container
        image: saif1198/symfonyapp:latest  # Ensure that the tag is specified for the image (e.g., latest)
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ENV_VARIABLE_NAME   # If any environment variables are needed
          value: "some_value"
        
---
apiVersion: v1
kind: Service
metadata:
  name: symfonyapp-service
spec:
  selector:
    app: symfonyapp
  ports:
    - protocol: TCP
      port: 80      # Port exposed by the service
      targetPort: 80 # Port the container is listening on
  type: NodePort   # If you want the service accessible externally
